# Generated by Django 4.2.16 on 2024-09-30 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0002_alter_ciudad_options_alter_comuna_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='codigo_region',
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_provincia', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('codigo_telefonico_provincia', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direcciones.region')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
    ]
