# Generated by Django 4.2.16 on 2024-10-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0003_remove_region_codigo_region_provincia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
