# Generated by Django 4.2.16 on 2024-10-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0004_delete_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre_pais',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
