# Generated by Django 4.2.16 on 2024-10-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0005_alter_pais_nombre_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre_pais',
            field=models.CharField(default='Desconocido', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
