# Generated by Django 4.2.16 on 2024-10-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0006_alter_pais_nombre_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='codigo_telefonico_provincia',
        ),
        migrations.AddField(
            model_name='region',
            name='codigo_telefonico_region',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
